feat(vault-agent): support for Vault-generated SSH CA host keys
Note that `sshd` will complain about these keys like so:

```
error: Public key for /etc/ssh/ssh_ca_host_ed25519_key does not match private key
```

However, it's wrong: the public key does match, and clients will
accept it without complaint. Therefore, it appears we can ignore this
error. (I'm not sure about the root cause. Perhaps it has something to
do with there being multiple ed25519 keys -- the self-signed one
generated by the service startup script, and the Vault-signed one.)

Signed-off-by: Drew Hess <src@drewhess.com>